// 临时菜单路由
export const tempMenus = [
  {
    id: 2,
    parentId: 1,
    level: 2,
    path: '1|2',
    name: '浏览器',
    icon: 'global',
  },
  {
    id: 3,
    parentId: 2,
    level: 3,
    path: '1|2|3',
    name: '浏览器类型',
    hashPath: '/brs/browsertype',
    chunkName: 'root-BrsBrowserType',
    moduleId: './src/areas/root/Brs/BrowserType/List.js',
  },
  {
    id: 4,
    parentId: 2,
    level: 3,
    path: '1|2|4',
    name: '浏览器',
    hashPath: '/brs/browser',
    chunkName: 'root-BrsBrowser',
    moduleId: './src/areas/root/Brs/Browser/List.js',
  },
  {
    id: 5,
    parentId: 2,
    level: 3,
    path: '1|2|5',
    name: '浏览器版本',
    hashPath: '/brs/browserversion',
    chunkName: 'root-BrsBrowserVersion',
    moduleId: './src/areas/root/Brs/BrowserVersion/List.js',
  },
  {
    id: 6,
    parentId: 1,
    level: 2,
    path: '1|6',
    name: '语言',
    icon: 'heat-map',
  },
  {
    id: 7,
    parentId: 6,
    level: 3,
    path: '1|6|7',
    name: '语言',
    hashPath: '/lan/language',
    chunkName: 'root-LanLanguage',
    moduleId: './src/areas/root/Lan/Language/List.js',
  },
  {
    id: 8,
    parentId: 1,
    level: 2,
    path: '1|8',
    name: '知识点',
    icon: 'book',
  },
  {
    id: 9,
    parentId: 8,
    level: 3,
    path: '1|8|9',
    name: '知识点类型',
    hashPath: '/kng/knowledgecategory',
    chunkName: 'root-KngKnowledgeCategory',
    moduleId: './src/areas/root/Kng/KnowledgeCategory/List.js',
  },
  {
    id: 10,
    parentId: 8,
    level: 3,
    path: '1|8|10',
    name: '知识点',
    hashPath: '/kng/knowledge',
    chunkName: 'root-KngKnowledge',
    moduleId: './src/areas/root/Kng/Knowledge/List.js',
  },
];

// 非菜单路由
export const nonMenuRouters = [
  {
    name: '登录',
    hashPath: '/auth/login',
    chunkName: 'shared-AuthLogin',
    moduleId: './src/areas/shared/Auth/Login.js',
  },
  {
    name: '工作台',
    hashPath: '/dashboard/workplace',
    chunkName: 'root-DsbWorkplace',
    moduleId: './src/areas/root/Dsb/Workplace.js',
  },
  {
    name: '403',
    hashPath: '/exception/403',
    chunkName: 'shared-Exception403',
    moduleId: './src/areas/shared/Exception/403.js',
  },
  {
    name: '404',
    hashPath: '/exception/404',
    chunkName: 'shared-Exception404',
    moduleId: './src/areas/shared/Exception/404.js',
  },
  {
    name: '500',
    hashPath: '/exception/500',
    chunkName: 'shared-Exception500',
    moduleId: './src/areas/shared/Exception/500.js',
  },
  {
    name: '500',
    hashPath: '/exception/500',
    chunkName: 'shared-Exception500',
    moduleId: './src/areas/shared/Exception/500.js',
  },
  // 知识点
  {
    id: 1001,
    parentId: 10,
    level: 4,
    path: '1|8|10|1001',
    name: '新建知识点',
    hashPath: '/kng/knowledge/new',
    chunkName: 'root-KngKnowledgeNew',
    moduleId: './src/areas/root/Kng/Knowledge/New.js',
  },
  {
    id: 1002,
    parentId: 10,
    level: 4,
    path: '1|8|10|1002',
    name: '编辑知识点',
    hashPath: '/kng/knowledge/edit',
    chunkName: 'root-KngKnowledgeEdit',
    moduleId: './src/areas/root/Kng/Knowledge/Edit.js',
  },
];

// 非菜单-子路由
export const childRouters = [
  {
    id: 12901,
    parentId: 129,
    level: 5,
    path: '1|2|126|129|12901',
    name: '公司',
    hashPath: '/org/all/company',
    chunkName: 'root-OrgPropertyProjectList',
    moduleId: './src/areas/root/Org/PropertyProject/List.js',
  },
];
